// app/api/line/setup-richmenu/route.ts
// LINE リッチメニューを作成・設定するエンドポイント
// POST /api/line/setup-richmenu  (X-Admin-Secret ヘッダー必須)
//
// 【使い方】
// curl -X POST https://gackt-chatbot.vercel.app/api/line/setup-richmenu \
//   -H "X-Admin-Secret: <ADMIN_SECRET の値>"
//
// 成功すると richMenuId が返る。以後は LINE Official Account Manager から
// 画像をデザインしたものに差し替え可能。

import { NextRequest, NextResponse } from 'next/server'

const LINE_API = 'https://api.line.me/v2/bot'

function authHeader() {
  return { Authorization: `Bearer ${process.env.LINE_CHANNEL_ACCESS_TOKEN}` }
}

/** リッチメニュー定義（2500×843px、4ボタン） */
const RICH_MENU = {
  size: { width: 2500, height: 843 },
  selected: true,
  name: 'GACKT公式メニュー',
  chatBarText: 'メニューを開く',
  areas: [
    {
      bounds: { x: 0, y: 0, width: 625, height: 843 },
      action: { type: 'message', label: 'ライブ情報', text: 'ライブ・コンサートの日程を教えてください' },
    },
    {
      bounds: { x: 625, y: 0, width: 625, height: 843 },
      action: { type: 'message', label: 'グッズ', text: 'グッズはどこで購入できますか？' },
    },
    {
      bounds: { x: 1250, y: 0, width: 625, height: 843 },
      action: { type: 'message', label: 'ファンクラブ', text: 'ファンクラブについて教えてください' },
    },
    {
      bounds: { x: 1875, y: 0, width: 625, height: 843 },
      action: { type: 'message', label: 'よくある質問', text: 'よくある質問を教えてください' },
    },
  ],
}

// プレースホルダー画像（4色ブロック 2500×843px PNG）
// ※ LINE Official Account Manager から差し替え可能
const RICH_MENU_IMAGE_B64 = 'iVBORw0KGgoAAAANSUhEUgAACcQAAANLCAIAAADqh5spAAAfRUlEQVR42u3bIU5DQRRAUUqaVGDQswWSnxTHQlglC6lrFVv4ugZBUlGDAP41489x8+Qzk8nN7MZYHgAAAAAAAAD469EKAAAAAAAAALbEVAAAAAAAAIAgpgIAAAAAAACE/e/D7fBsIwAwd5V+X7fDr/FqMwAw5Wk9b4dv491mAGDKaf3YDi8vXqkAMOf4+fNK9TMVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAhiKgAAAAAAAEAQUwEAAAAAAACCmAoAAAAAAAAQxFQAAAAAAACAIKYCAAAAAAAABDEVAAAAAAAAIIipAAAAAAAAAEFMBQAAAAAAAAi7MRZbAAAAAAAAAPjHz1QAAAAAAACAIKYCAAAAAAAAhDsDgBNbQlLbOwAAAABJRU5ErkJggg=='

export async function POST(request: NextRequest) {
  const adminSecret = request.headers.get('x-admin-secret')
  if (!adminSecret || adminSecret !== process.env.ADMIN_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const accessToken = process.env.LINE_CHANNEL_ACCESS_TOKEN
  if (!accessToken) {
    return NextResponse.json({ error: 'LINE_CHANNEL_ACCESS_TOKEN not set' }, { status: 500 })
  }

  try {
    // Step 1: リッチメニューを作成
    const createRes = await fetch(`${LINE_API}/richmenu`, {
      method: 'POST',
      headers: { ...authHeader(), 'Content-Type': 'application/json' },
      body: JSON.stringify(RICH_MENU),
    })
    if (!createRes.ok) {
      const err = await createRes.text()
      throw new Error(`リッチメニュー作成失敗: ${createRes.status} ${err}`)
    }
    const { richMenuId } = await createRes.json() as { richMenuId: string }

    // Step 2: 画像をアップロード
    const imgBuffer = Buffer.from(RICH_MENU_IMAGE_B64, 'base64')
    const uploadRes = await fetch(`https://api-data.line.me/v2/bot/richmenu/${richMenuId}/content`, {
      method: 'POST',
      headers: { ...authHeader(), 'Content-Type': 'image/png' },
      body: imgBuffer,
    })
    if (!uploadRes.ok) {
      const err = await uploadRes.text()
      throw new Error(`画像アップロード失敗: ${uploadRes.status} ${err}`)
    }

    // Step 3: デフォルトリッチメニューとして全ユーザーに設定
    const setDefaultRes = await fetch(`${LINE_API}/user/all/richmenu/${richMenuId}`, {
      method: 'POST',
      headers: authHeader(),
    })
    if (!setDefaultRes.ok) {
      const err = await setDefaultRes.text()
      throw new Error(`デフォルト設定失敗: ${setDefaultRes.status} ${err}`)
    }

    return NextResponse.json({
      ok: true,
      richMenuId,
      message: 'リッチメニューのセットアップが完了しました。LINE Official Account Managerから画像を差し替えてください。',
    })
  } catch (error) {
    console.error('[setup-richmenu] Error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 },
    )
  }
}
